name: Release - Tag Triggered

on:
  push:
    tags: ['v*']

env:
  NODE_VERSION: '20'

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=v${VERSION}" >> $GITHUB_OUTPUT

  build-mac-dmg:
    name: Build macOS DMG
    runs-on: macos-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Package macOS DMG
        run: npm run package:mac:dmg
        
      - name: Upload DMG artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg-${{ needs.prepare.outputs.version }}
          path: |
            dist/*.dmg
          retention-days: 90

  build-mac-zip:
    name: Build macOS ZIP (Auto-updater)
    runs-on: macos-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Package macOS ZIP
        run: npm run package:mac:zip
        
      - name: Generate auto-updater metadata
        run: |
          ZIP_FILE=$(ls dist/*.zip | head -1)
          ZIP_NAME=$(basename "$ZIP_FILE")
          ZIP_SIZE=$(stat -f%z "$ZIP_FILE")
          ZIP_SHA512=$(shasum -a 512 "$ZIP_FILE" | cut -d' ' -f1)
          BLOCKMAP_FILE="${ZIP_FILE}.blockmap"
          BLOCKMAP_SIZE=$(stat -f%z "$BLOCKMAP_FILE" 2>/dev/null || echo "0")
          
          cat > dist/latest-mac.yml << EOF
          version: ${{ needs.prepare.outputs.version }}
          files:
            - url: ${ZIP_NAME}
              sha512: ${ZIP_SHA512}
              size: ${ZIP_SIZE}
              blockMapSize: ${BLOCKMAP_SIZE}
          path: ${ZIP_NAME}
          sha512: ${ZIP_SHA512}
          releaseDate: $(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")
          EOF
          
          echo "Generated latest-mac.yml:"
          cat dist/latest-mac.yml
        
      - name: Upload ZIP artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-zip-${{ needs.prepare.outputs.version }}
          path: |
            dist/*.zip
            dist/*.blockmap
            dist/latest-mac.yml
          retention-days: 90

  build-linux-deb:
    name: Build Linux DEB
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm-dev libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libxss1 libasound2-dev
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Package Linux DEB
        run: npm run package:linux:deb
        
      - name: Generate Linux auto-updater metadata
        run: |
          DEB_FILE=$(ls dist/*.deb | head -1)
          DEB_NAME=$(basename "$DEB_FILE")
          DEB_SIZE=$(stat -c%s "$DEB_FILE")
          DEB_SHA512=$(sha512sum "$DEB_FILE" | cut -d' ' -f1)
          
          cat > dist/latest-linux.yml << EOF
          version: ${{ needs.prepare.outputs.version }}
          files:
            - url: ${DEB_NAME}
              sha512: ${DEB_SHA512}
              size: ${DEB_SIZE}
          path: ${DEB_NAME}
          sha512: ${DEB_SHA512}
          releaseDate: $(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")
          EOF
          
          echo "Generated latest-linux.yml:"
          cat dist/latest-linux.yml
        
      - name: Upload DEB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb-${{ needs.prepare.outputs.version }}
          path: |
            dist/*.deb
            dist/latest-linux.yml
          retention-days: 90

  build-linux-tar:
    name: Build Linux TAR.GZ
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm-dev libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libxss1 libasound2-dev
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Package Linux TAR.GZ
        run: npm run package:linux:tar
        
      - name: Upload TAR.GZ artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-tar-${{ needs.prepare.outputs.version }}
          path: |
            dist/*.tar.gz
          retention-days: 90

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [prepare, build-mac-dmg, build-mac-zip, build-linux-deb, build-linux-tar]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -name "*.dmg" -o -name "*.zip" -o -name "*.deb" -o -name "*.tar.gz" -o -name "*.blockmap" -o -name "latest-*.yml" | xargs -I {} cp {} release-assets/
          ls -la release-assets/
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare.outputs.tag }}
          name: CCTracker ${{ needs.prepare.outputs.version }}
          files: release-assets/*
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## CCTracker ${{ needs.prepare.outputs.version }}
            
            ### 📦 Downloads
            
            **macOS:**
            - `CCTracker-${{ needs.prepare.outputs.version }}-mac-universal.dmg` - macOS Universal Binary (Intel + Apple Silicon)
            
            **Linux:**
            - `CCTracker-${{ needs.prepare.outputs.version }}-linux-x64.deb` - Debian/Ubuntu Package
            - `CCTracker-${{ needs.prepare.outputs.version }}-linux-x64.tar.gz` - Linux Tarball
            
            ### 🔄 Auto-Update
            This release includes automatic update functionality with proper metadata files.
            
            ### 📋 Installation
            
            **macOS:** Download `.dmg` and drag to Applications
            **Linux:** Install `.deb` with `sudo dpkg -i` or extract `.tar.gz`